#code attribution
#author: Zahava Gopin
#title: gopin-composers.yaml
#description: composers api
#date: 3/2/2023
openapi: "3.0.0"
info:
 title: composers
 version: "1.0"
paths:
 /composers:
    get:
      tags: 
        - composers
      description: |
        API for returning a list of composers from MongoDB Atlas.
      summary: |
        returns a list of composer documents
      responses:
        '200':
          description: Composer documents
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    post:
      tags:
        - composers
      description: Creates new composer objects
      summary: Creates a composer object
      requestBody:
        description: Composer information
        content:
          application/json:
            schema:
              required:
                - type
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: composer added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
 /composers/{id}:
    get:
      tags:
        - composers
      description: |
        API for returning a composer document
      summary: |
        returns a composer document
      parameters:
        - name: id
          in: path
          required: true
          description: |
            The composer requested by the user.
          schema:
            type: string
      responses:
        '200':
          description: Composer document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception